### ISSUE TITLE
Support for Adaptive Lighting?

### ISSUE THREAD

**Issue by macjl** [RavenSystem/esp-homekit-devices#1147]
Hello,

I understood that Adaptive Lighting, that was added to iOS 14, would need an update on accessories side to be enabled. 
Do you know if you will be able to provide such support for lightbulb devices with HAA?

**Comment by bj-tracer** [comment]
Hmmm...
It's a homekit automation function as i know.
Device must have color temperature adjustment only.

**Comment by macjl** [comment]
Not only. There are new characteristics for that : 
https://github.com/ebaauw/homebridge-hue/issues/766

**Comment by lcges** [comment]
Hey, are you planning to add Adaptive Lighting support to your driver?

**Comment by MikeyBally** [comment]
Would love this!

**Comment by peros550** [comment]
+1

**Comment by macjl** [comment]
FYI, homebridge-hue is now working with Adaptive Lightning : https://github.com/ebaauw/homebridge-hue/issues/766
I juste tested it, and it works nice! Maybe you could find informations about how to include it in HAA in the repository?

**Comment by mwwgithub** [comment]
This would be a game changer for me.  Right now I’m primarily using WiZ bulbs and recessed lights that are exposed to HomeKit via HomeBridge, partly because I like that the WiZ lights can autonomously follow a set rhythm for color temperature.  

However the Feit recessed lights that can run this firmware have a much nicer design with a recessed lens to reduce glare.  But I’d miss the “follow the sun” color temperature.

**Comment by lcges** [comment]
What status is the thread on?

**Comment by mwwgithub** [comment]
I'd love to know the same.  Any chance this can be implemented?

**Comment by RavenSystem** [comment]
I have no plans to include Apple Adaptive Lighting. However, you can use timetable actions and lightbulb service notification to create and customize your own Adaptive Lighting system.
