### ISSUE TITLE
haa_downloader.sh, small correction suggestion

### ISSUE THREAD

**Issue by peking84** [RavenSystem/esp-homekit-devices#1252]
haa downloader sh (https://github.com/RavenSystem/haa) shall have a -p when issuing mkdir, otherwise directory cannot be created and download will fail on the very first run.

instead:
```
	if [ -z "$validation" ]
	then
		if [ ! -d "$webroot/haa/$version" ]; then
			mkdir "$webroot/haa/$version"
		fi

```
```
	if [ -z "$validation" ]
	then
		if [ ! -d "$webroot/haa/$version" ]; then
			mkdir -p "$webroot/haa/$version"
		fi

```

error as visible:

```
$ ./haa_downloader.sh

=============================================================
HAA Binary Downloader Copyright (C) 2020  AJAX
This program comes with ABSOLUTELY NO WARRANTY;
This is free software, and you are welcome to redistribute it
under certain conditions.
See the GNU General Public License for more details.
=============================================================

Attempting to download the latest version: 4.0.1
--------------------------------------------------------

mkdir: cannot create directory â/volume4/web/haa/4.0.1â: No such file or directory
Saving /volume4/web/haa/4.0.1/fullhaaboot.bin ... Failed to retrieve, check connection or user permissions
Saving /volume4/web/haa/4.0.1/haaboot.bin ... Failed to retrieve, check connection or user permissions

```

**Comment by wayn3** [comment]
Ahh yes I did actually notice this but forgot to fix it... also not sure how to assign this issue to me

Rather than implementing -p param I'll check if the directory exists during configuration and create it at that point in time as I would prefer for it to fail if the selected webroot doesn't actually exist and not to create a nested directory structure for a web server that they aren't actually using but I appreciate the ticket and good to know people are getting use out of it :)
