### ISSUE TITLE
OTA Downgrade feature

### ISSUE THREAD

**Issue by i3laze** [RavenSystem/esp-homekit-devices#1485]
There are good days and some bad days: 
the ones you upgrade to a bleeding edge HAA firmware with a bug, which is not fixed yet or with a behavior changed.

Personally, I suspect v6.7.2 just broken my “leak” contact sensor, but have no instant option to downgrade to check the theory.  (Yeah-yeah, get own webserver running e.t.c.)

**Feature request for Setup mode:**
 _An input field “Downgrade to specific version” to manually specify older release like “6.3.0”._

Seems to be compatible with GitHub folder structure and would Not require querying a list of recent firmware releases.

UPD: False alarm: after visual inspection pond water level is indeed low, however the feature request stands.

**Comment by peros550** [comment]
I think, someone does not need their own server to effectively downgrade.  On the setup page, at the custom server filed you can put: 

github.com/RavenSystem/haa/releases/download/x.x.x

With x.x.x the version you would require to downgrade to. 

Tip: Some releases may have removed assets because of issues. First check here (https://github.com/RavenSystem/haa/releases) if your version you are looking for has the required assets and if yes, you can proceed.

**Comment by i3laze** [comment]
Nice tip, thanks!
I suggest to make this exact GitHub url/method wrapped in an easy accessible feature (which desk not require searching all the Wiki and Issues sections).

**Comment by pilot1981** [comment]
I agree: this could be a great feature/enhancement!

**Comment by RavenSystem** [comment]
Downgrade is done using custom server. There is not needed of having separate fields for URL and version. I will update Wiki with info about installing a specific version ASAP.
