### ISSUE TITLE
Enhancement request - Homekit device with notification

### ISSUE THREAD

**Issue by claire078** [RavenSystem/esp-homekit-devices#185]
Hi,

I already try to write me ask in another topic (Motion sensor), but better when I make a separate one.
I'd like to use a Sonoff device which can notify me when its status has changed. (operated with GPIO14 or 02).
Is that possible?
Thanks.

**Comment by peros550** [comment]
Hi Claire , if the the firmware is designed to expose a motion sensor you could connect one to the assigned GPIO and then set its settings in order to receive status notifications. The notifications are delivered by the iOS/tvOS, so no need for firmware adjustments. The only thing needed is just the firmware to expose a motion sensors. ![GitHawk Upload by peros550](https://i.imgur.com/cLsUKzl.jpg)

![GitHawk Upload by peros550](https://i.imgur.com/mmzXjS8.jpg)

![GitHawk Upload by peros550](https://i.imgur.com/nbNvYv0.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by seritos** [comment]
I think this is an enhacemnt already included in the TODO list. 
I am also very interested in this usefull feature

**Comment by claire078** [comment]
Thanks for the confirmation. 😉
