### ISSUE TITLE
No wildcard trigger on brightness=0

### ISSUE THREAD

**Issue by plisherness** [RavenSystem/esp-homekit-devices#1879]
I have a light strip with warm white and cool white LEDs, which I want to operate as a single "dim to warm" channel - where 100% brightness is WW=1.0,CW=1.0, and then as it dims, the CW dims first and then the WW dims, shifting the temperature to warmer when it is dimmer like an incandescent bulb might.

Before the latest update, I had this working with 1 virtual lightbulb that sent service notifications to 2 hidden lightbulbs. With the latest update this broke, specifically for the case that the bulb is turned off by setting the brightness to 0. From the debug output, it seems that the wildcard for brightness=0 never triggers, and additionally, the "0" action for the bulb turning off never fires either. So the hidden lightbulbs just remain in whatever state they last were instead of turning off.

I also tried adding "r":1 to the brightness 0 wildcard, and this did not seem to help. My configuration:

`{"c":{"o":3,"l":2,"b":[{"g":13,"t":5}]},"a":[{"t":30,"s":5,"g":[14],"h":0},{"t":30,"s":5,"g":[4],"h":0},
{"t":30,"s":5,"ty":0,
"0":{"m":[[1,2],[2,2],[1,0],[2,0]]},
"1":{"m":[[1,1],[2,1]]},
"y0":[
	{"v":0,"r":1,"0":{"m":[[1,1],[2,1],[1,2],[2,2]]}},
	{"v":1,"0":{"m":[[1,1],[2,1],[1,3],[2,2]]}},
	{"v":5,"0":{"m":[[1,1],[2,1],[1,7],[2,2]]}},
	{"v":10,"0":{"m":[[1,1],[2,1],[1,12],[2,2]]}},
	{"v":15,"0":{"m":[[1,1],[2,1],[1,20],[2,2]]}},
	{"v":20,"0":{"m":[[1,1],[2,1],[1,30],[2,2]]}},
	{"v":25,"0":{"m":[[1,1],[2,1],[1,40],[2,2]]}},
	{"v":30,"0":{"m":[[1,1],[2,1],[1,50],[2,2]]}},
	{"v":35,"0":{"m":[[1,1],[2,1],[1,60],[2,2]]}},
	{"v":40,"0":{"m":[[1,1],[2,1],[1,70],[2,2]]}},
	{"v":45,"0":{"m":[[1,1],[2,1],[1,80],[2,2]]}},
	{"v":50,"0":{"m":[[1,1],[2,1],[1,90],[2,2]]}},
	{"v":55,"0":{"m":[[1,1],[2,1],[1,102],[2,2]]}},
	{"v":60,"0":{"m":[[1,1],[2,1],[1,102],[2,12]]}},
	{"v":65,"0":{"m":[[1,1],[2,1],[1,102],[2,22]]}},
	{"v":70,"0":{"m":[[1,1],[2,1],[1,102],[2,32]]}},
	{"v":75,"0":{"m":[[1,1],[2,1],[1,102],[2,42]]}},
	{"v":80,"0":{"m":[[1,1],[2,1],[1,102],[2,52]]}},
	{"v":85,"0":{"m":[[1,1],[2,1],[1,102],[2,62]]}},
	{"v":90,"0":{"m":[[1,1],[2,1],[1,102],[2,72]]}},
	{"v":95,"0":{"m":[[1,1],[2,1],[1,102],[2,82]]}},
	{"v":98,"0":{"m":[[1,1],[2,1],[1,102],[2,92]]}},
	{"v":100,"0":{"m":[[1,1],[2,1],[1,102],[2,102]]}}
]
}]}
`

**Comment by andyallcorn** [comment]
I have also noticed that on/off actions do not fire if the slider is used rather than a tap on the bulb from the main HomeKit view. It’s not how I expected it to work, but I’ve worked around it.

I also confirm the experience with brightness=0 not triggering — but I believe this is _only if you have an action set for brightness=1_, as you do in this json. I have worked around this by setting my lowest action as brightness=2 instead, which works fine, although it is not the way I had instinctively set it up. I haven’t tried using brightness=1 in my json since I discovered the problem roughly a year ago as I am content with the workaround, but this is a long-standing situation.
