### ISSUE TITLE
Thermostat 

### ISSUE THREAD

**Issue by Gio1978** [RavenSystem/esp-homekit-devices#212]
Does thermostat has this  feature?  if temp <= 21 it turns on heat... if temp >= 21.2 it turns off heating

**Comment by digiservice2001** [comment]
I think +/- 0.5 C hysterisis is better. Most of thermostats work like this. Less on/off switching, and that's comfortable.

  ----- Original Message ----- 
  From: Gio1978 
  To: RavenSystem/esp-homekit-devices 
  Cc: Subscribed 
  Sent: Saturday, January 26, 2019 12:14 PM
  Subject: [RavenSystem/esp-homekit-devices] Thermostat (#212)


  Does thermostat has this future? if temp <= 21 it turns on heat... if temp >= 21.2 it turns off heating

  —
  You are receiving this because you are subscribed to this thread.
  Reply to this email directly, view it on GitHub, or mute the thread.


---
Ezt az e-mailt az Avast víruskereső szoftver átvizsgálta.
https://www.avast.com/antivirus

**Comment by RavenSystem** [comment]
To avoid switching abuse, increase poll period.
