### ISSUE TITLE
Fast power accuracy

### ISSUE THREAD

**Issue by Tellicious** [RavenSystem/esp-homekit-devices#2142]
Hi José, I noticed you're using the fast power algorithm from this [link](https://martin.ankerl.com/2012/01/25/optimized-approximative-pow-in-c-and-cpp/), however its accuracy varies significantly depending on the input values, but usually is in the range of +- 4/5 %.

Given that its author himself states that it is just ~3.3 times faster than standard  `pow()`, is it really needed to trade off accuracy for speed on a task that is expected to run every several seconds and that is not time critical?

(FYI There are also other some more sophisticated attempts at making a fast precise power, such as [this one](https://jrfonseca.blogspot.com/2008/09/fast-sse2-pow-tables-or-polynomials.html))

**Comment by RavenSystem** [comment]
Hello,

Reason for use this algorithm is not speed, is size. Current HAA version is only about 100 bytes left to reach binary limit for esp8266, however, esp32, 32c and 32s could use `pow()` instead, because total size for HAA is 2MB instead 1MB. I will switch to it in next version, but not for esp8266. If I need more space for 32, 32c... in the future, I will back to `fast_precise_pow()`, but I do not think that happens.
