### ISSUE TITLE
Issue with has stop step on garage door opener

### ISSUE THREAD

**Issue by pilot1981** [RavenSystem/esp-homekit-devices#270]
Hi,
I tried to use has stop step but I’m not sure it work well..
I setup “has stop step” ON, but if I say “Siri stop door” or “Siri restart door” Siri don’r Recognize this command...

I’m sure door accept stop step command because if I say “Siri open door” or “Siri close door” during opening/closing of door, door stop immediately...

Anyone know right command to send to Siri?

**Comment by RavenSystem** [comment]
You can not stop your garage door using HomeKit. Apple has not implement that feature. The “has stop step” ON is to use 2 relay activations instead 1 when door is moving. For example, if your door is opening, and you want to close it, now it will close instead stop, because 2 relays activations (first stops it, and second closes it).
