### ISSUE TITLE
DHT11 without switch

### ISSUE THREAD

**Issue by cadetandrey** [RavenSystem/esp-homekit-devices#312]
Hi
How about new device type temperature DhT sensor only ?
Thank you

**Comment by lizzus** [comment]
Yes! I’d like it!!! I found this object with esp01s and ds18b20 sensor.

https://ibb.co/3Rbrs7k

**Comment by cadetandrey** [comment]
Today add same sensor with dht11
set board 2 device 6 and have switch ))

**Comment by lizzus** [comment]
This have not a relay! What do you do for have a switch?

**Comment by cadetandrey** [comment]
Yes, have not relay, but in homekit I have switch unused

**Comment by RavenSystem** [comment]
RavenCore does not support it. You must wait until HAA firmware is released.

**Comment by lizzus** [comment]
Why not supper it?

**Comment by pandarek** [comment]
@lizzus try this:
https://github.com/pandarek/esp-homekit-demo/tree/master/examples/temperature_sensor
If you can not do a compilation and set up a GPIO for the TH sensor, I can sort the bin.

**Comment by lizzus** [comment]
@pandarek , please contact to my email lizzus[at]me.com thanks

**Comment by RavenSystem** [comment]
> Why not supper it?

Because RavenCore is focused to work with Sonoff devices. HAA will support it, because it is focused in all kind of devices, including custom devices.

**Comment by lizzus** [comment]
but inside ravencore esp01s is present. I use with device 10.  
Esp01 is economic and versatile... We can use for motion or themperature sensor...

**Comment by RavenSystem** [comment]
@lizzus Yes, but I included esp01 for a personal custom project, and it was a bad idea. Because Esp01 is  versatile, there are many possible options to customize. RavenCore uses custom HomeKit characteristics to customize the device, and when a new custom HomeKit characteristics is created, performance lows a bit. Actually, I keep performance in a very good level, but I can not add the necessary characteristics to create a enough versatile custom device. That is the reason because I am developing HAA firmware: you will provide a json string to configure device instead using custom HomeKit characteristics.
