### ISSUE TITLE
possible upgrade 9) window rolling shutter

### ISSUE THREAD

**Issue by oremic** [RavenSystem/esp-homekit-devices#32]
hi
Excellent work, congratulations.
For the dual sonoff you can create setting 9). Window / shutters.
Creating adjustable timings on eve app.
has two relays one for the ascent one for the descent.
by setting the descent time and the rise time, the position of the window is also calculated.
Linking button 0 for the ascent and button 1 for the descent as physical buttons.

**Comment by RavenSystem** [comment]
Many thanks for your suggestion.

**Comment by peros550** [comment]
Recently I have created a board to control my rolling shutters remote control and used homebridge to integrate it into homekit and see it as a shutter accessory there.  

My experience says that it is much easier to achieve the control part but quite tricky to achieve the reporting of current position. This is because current position of the shutters could be changed  when the shutters can be controlled from a source outside of this system (i.e. RF remote control or wall switch) hence home app will not be in sync anymore with real position. 

It's a very interesting enhancement though.

**Comment by RavenSystem** [comment]
Is neccesary a sensor to control current position. This is an advandced version of a garage door. Advanced because a garage door doesn’t keep middle open, but a shutter yes. I am going to develop garage door first, and shutters will be after in a future.

**Comment by oremic** [comment]
@peros550 
The external source veins connected to the botton1 for the ascent and to the botton 2 for the descent so the position will always be consistent, with that of the app.

@RavenSystem 
Surely with an incremental encoder the position would be perfect.
But I already use a system of this type and it works very well, calculating perfectly the rise time and the time of descent are able to always have the position of the rolling shutter.

**Comment by RavenSystem** [comment]
This will be possible when saved states is implemented, because position must be saved to flash to avoid problem with reboots and initial shutter position.

**Comment by RavenSystem** [comment]
Added to TODO list: https://github.com/RavenSystem/esp-homekit-devices/wiki/TODO-List
