### ISSUE TITLE
homekit-divices have no hostname in router

### ISSUE THREAD

**Issue by douzs** [RavenSystem/esp-homekit-devices#472]
hey,
I have a little question:
I have a lot of devices which  flashed the firmware and I can't distinguish them in the router. They have no hostname in router.
I want to konw how to give them name like RavenCore-%02X%02X%02X 
I mean the source code can change to solve the little problem ,or not?

thank you

**Comment by peros550** [comment]
Was this included in latest version ?

**Comment by RavenSystem** [comment]
No, but code is ready. I want to test right. It will be available with next version.

**Comment by mafyata** [comment]
How can I change the hostname? I updated my devices and entered in setup mode to see is there a way to change it , but nothing.

**Comment by RavenSystem** [comment]
https://github.com/RavenSystem/esp-homekit-devices/wiki/Home-Accessory-Architect#n-custom-hostname

**Comment by douzs** [comment]
@RavenSystem That's so greate! thank you

**Comment by peros550** [comment]
Man! We can’t keep up with your pace! 
And I still haven’t had the chance to try the RestAPI feature :):):)):)

Thank you Jose!

**Comment by macjl** [comment]
Thank you Jose for this feature. I have tested it, and it works great on the network. I can access to my devices with custom hostname.

I have noticed that on Homekit side, the devices still have the HAA-xxxxxx name in Home App. Is it wanted ?

**Comment by RavenSystem** [comment]
> I have noticed that on Homekit side, the devices still have the HAA-xxxxxx name in Home App. Is it wanted ?

Yes, it is wanted. It must be unique to avoid issues with HAP, and it must be short, to use less memory. That name is used with mDNS/Bonjour service. But then you can rename HomeKit services into Home App (Internally, HAA-XXXXXX is used to manage accessory).

Other feature is that you can change device hostname in any moment, and you will keep all HomeKit settings, because mDNS name is the same always. In other case, you will must reset HomeKit ID and repair device when you change device hostname.
