### ISSUE TITLE
Questions: HAA

### ISSUE THREAD

**Issue by claire078** [RavenSystem/esp-homekit-devices#561]
Sonoff SV already supported with HAA firmware?

**Comment by RavenSystem** [comment]
All devices with an esp8266/esp8285 chip are supported.

**Comment by claire078** [comment]
The templates are labeled in HAA templates. Sonoff mini, Jelly, etc. 
That is why I asked it. Then just because the IO names are different?

**Comment by RavenSystem** [comment]
What do you ask with "Then just because the IO names are different?"? I don't understand question.

**Comment by claire078** [comment]
Why do templates have labels Sonoff mini, Jelly etc. ?

**Comment by RavenSystem** [comment]
Because they use GPIOs of labeled devices.

**Comment by claire078** [comment]
Possible to enter setup mode with Homekit button without trigger the relay? For example push and hold the button in Home app without switch the relay. 
I have some devices wich are not easy to access.

**Comment by RavenSystem** [comment]
No, HomeKit is not prepare to send push and hold events from Apps. If you want to enter setup mode without accessing device and without trigger relay, you must declare an additional HomeKit switch without actions, so you can use it to enter setup mode toggling quickly it. Because HAA supports multiroom, you can move that "dummy" switch to other room.

**Comment by claire078** [comment]
Every device with one dummy switch? 😳
In action mode (not setup mode) could able to switch device with its ip address (webpage) to setup mode?

**Comment by RavenSystem** [comment]
No, sorry. You must see device IP address in your DHCP server.
