### ISSUE TITLE
Sonoff Dual - HAA code

### ISSUE THREAD

**Issue by hexardavies** [RavenSystem/esp-homekit-devices#579]
Have had it working over the weekend. works great. try it.

{"c": {"l": 13,"b": [{"g": 10}]},"a": [{"0": {"r": [{"g": 5}]},"1": {"r": [{"g": 5,"v": 1}]},"b": [{"g": 0}]},{"0": {"r": [{"g": 12}]},"1": {"r": [{"g": 12,"v": 1}]},"b": [{"g": 9}]}]}

**Comment by RavenSystem** [comment]
Many thanks.!

**Comment by sercitecotf** [comment]
and in switch mode instead of switch, how would it be?

**Comment by RavenSystem** [comment]
@sercitecotf 

`{"c":{"l":13,"b":[{"g":10}]},"a":[{"0":{"r":[{"g":5}]},"1":{"r":[{"g":5,"v":1}]},"b":[{"g": 0},{"g":0,"t":0}]},{"0":{"r": [{"g":12}]},"1": {"r":[{"g":12,"v":1}]},"b":[{"g":9},{"g":9,"t":0}]}]}`

But it is not recommended, because when gpio 0 is pushed, device will not boot because it will enter in flash mode. To use with 2 switches instead buttons, Shelly 2.5 is better.
