### ISSUE TITLE
Shelly 1 switch as electric door mechanism trigger 

### ISSUE THREAD

**Issue by morphix9** [RavenSystem/esp-homekit-devices#714]
Shelly 1 
action: holding the relay open for 5 seconds
default state is closed/locked

**Comment by dominikkosciolek** [comment]
{"c":{"b":[{"g":5,"p":0,"i":1,"t":5}]},
"a":[
{
"t": 4,
"0":{"r":[{"g":4,"v":1}]},
"1":{"r":[{"g":4}]},
"i": 5
"b":[{"g":5}]
}
]}

**Comment by RavenSystem** [comment]
`{"c":{"b":[{"g":5,"p":0,"i":1,"t":5}]},"a":[{"t": 4,"i":5,"0":{"r":[{"g":4,"v":1}]},"1":{"r":[{"g":4}]},"b":[{"g":5}]}]}`

**Comment by morphix9** [comment]
Works like a charm, thanks!

**Comment by lickonline** [comment]
looked also for a json for a electric door mechanism
this json works perfect, thank you (all)!
_______________________________________
I changed to a triggering time of 2.5s, because 5s is a bit too long for my needs
I changed to a reboot state "locked", because I don*t want to open the door, when rebooting

json with the two small modifications:
{"c":{"b":[{"g":5,"p":0,"i":1,"t":5}]},"a":[{"0":{"r":[{"g":4,"v":1}]},"1":{"r":[{"g":4}]},"t":4,"i":2.5,"b":[{"g":5}],"s":1}]}
