### ISSUE TITLE
Control LED lights with integrated dimming function (push DIMM)

### ISSUE THREAD

**Issue by morphix9** [RavenSystem/esp-homekit-devices#766]
Hey guys,

I have LED lights with integrated dimming function. It works with push buttons - if you press less than 1s you turn it on/off. If you press for more than 1s you can make them brighter or darker. The lights have constant load.

Would that be possible to be driven with a Shelly 1 and HAA? I guess dimming would be hard to work with HomeKit, because the state/orientation cannot be known. But turning on/off should be possible or? For on/off it should open the relay for ~1s. Could that work together with the installed push button?

**Comment by mriksman** [comment]
Yeah I have the same question. Sort of.
Let's say you had just a ESP dimmer with a single GPIO input/button. Is there a JSON that can do what you say; if you press less than 1s you turn it on/off. If you press for more than 1s you can make them brighter or darker. 
I'm happy with the PWM output - because I am building a circuit board (using the FL5150 chip) that will take a PWM input and do a trailing edge dimming; perfect for AC LED Dimmable bulbs.
