### ISSUE TITLE
How to compile haa by myself on windows pc ?

### ISSUE THREAD

**Issue by tomekmatlacz** [RavenSystem/esp-homekit-devices#802]
Hello .Im new on github but i want to compile myself haa.
Now i install and start GIT Bash application.
Then i make command 👍 
`git clone https://github.com/RavenSystem/esp-homekit-devices/`

Next i done commands:
`cd esp-homekit-devices/`
`git submodule update --init --recursive`

Next i done
` git clone --recursive https://github.com/pfalcon/esp-open-sdk.git`

but when i send command 
`make STANDALONE=y`
I get 
`bash: make: command not found`

What i done wrong ?

**Comment by wwns** [comment]
******************************************************************************************
HomeKit Raven HAA building own firmware - Debian - Win10 -Rasbperry
******************************************************************************************
In windows 10  you must install subsystem, linux debian
https://docs.microsoft.com/en-us/windows/wsl/install-win10
Microsoft Store https://www.microsoft.com/store/productId/9MSVKQC78PK6
###############################################
sudo apt-get update
sudo apt-get upgrade
sudo install mc   -install Midnight Commander
###############################################
1.
sudo apt-get install make unrar-free autoconf automake libtool gcc g++ gperf \
    flex bison texinfo gawk ncurses-dev libexpat-dev python-dev python python-serial \
    sed git unzip bash help2man wget bzip2
2.
sudo apt-get install libtool-bin
3.
sudo apt-get install libz-dev
4.
git clone --recursive https://github.com/RavenSystem/esp-homekit-devices.git 
5.
git clone --recursive https://github.com/pfalcon/esp-open-sdk.git
6.
sudo nano esp-open-sdk/crosstool-NG/configure.ac go to line 193 and replace
paste and replace: 
|$EGREP '^GNU bash, version ([0-9\.]+)')
7.
we don't want to watch the build because it takes a long time
sudo apt-get install screen
screen bash
close CTRL + A push button D
show screen 
screen -lismct
we will see this result screen     -r 25788.pts-0.dev
closes completely without warning CTRL + D 
A.
make toolchain esptool libhal STANDALONE=n
8.
sudo nano /etc/profile
paste at the end of the file
export PATH=/home/pi/esp-open-sdk/xtensa-lx106-elf/bin:$PATH
9.
export PATH=/home/pi/esp-open-sdk/xtensa-lx106-elf/bin:$PATH
10.
make -C devices/HAA_LCM all
make -C devices/HAA all

**Comment by tomekmatlacz** [comment]
Thanks.
