### ISSUE TITLE
Can the garage door support 3 buttons?

### ISSUE THREAD

**Issue by 88adong88** [RavenSystem/esp-homekit-devices#94]
Type8 Garage door is very nice~~
but only support 1 button
Can the garage door support 3 buttons?（up+stop+down or up+down）

**Comment by RavenSystem** [comment]
Buttons are similar to relays. Actually, garage door dev tyle only supoorts 1 button because is focused on Sonoff with 1 relay, but a version with 2 relays (2 buttons) could be possible with Sonoff dual, because this device has 2 gpios to use with buttons, in this case, with opened and closed garage door sensors.
