### ISSUE TITLE
Sonoff randomly turning on. Baffled. 

### ISSUE THREAD

**Issue by bencharlesrhys** [RavenSystem/esp-homekit-devices#971]
I have several Sonoff Basic and 2ch switches and they inexplicably will pick a time to just all turn on at once. I can’t explain or find a pattern for this. It’s across many devices. It’s not based on time or any particular action I’m doing and they aren’t set up in any automations. It happens rarely and sometimes not for a week or two.

It will happen in the middle of the night, when I’m not home or some time during the day.

Some are running RavenSystem, others are gruppios plugin.

I’m trying to start logging to see what the cause is as it is wasting a lot of energy and I can’t use them on certain devices.

How would I access the logs once I’ve noticed an event?

**Comment by i3laze** [comment]
That’s called Ghost switching - google for it.
Regarding HAA you could try enable pull-up resistor on the input GPIO.

In my case I had wall switches (connected to Sonoff Basic and Shelly.Cloud devices) with a small embed LED (glowing at night), which actually led to electricity flowing through the switch to device even when the switch was off. This LED actually caused the ghost switching and I just removed it (luckily it was a removable option, otherwise wall switch should have been replaced).
